# from tkinter import Tk, StringVar, ttk
from tkinter import *

var1 = IntVar()
var2 = IntVar()
var3 = IntVar()
var4 = IntVar()
var5 = IntVar()
var6 = IntVar()
var7 = IntVar()
var8 = IntVar()
var9 = IntVar()
var10 = IntVar()
var11 = IntVar()
var12 = IntVar()
var13 = IntVar()
var14 = IntVar()
var15 = IntVar()
var16 = IntVar()
var17 = IntVar()
var18 = IntVar()
var19 = IntVar()
var20 = IntVar()
var21 = IntVar()
var22 = IntVar()
var23 = IntVar()
var24 = IntVar()

var1.set(0)
var2.set(0)
var3.set(0)
var4.set(0)
var5.set(0)
var6.set(0)
var7.set(0)
var8.set(0)
var9.set(0)
var10.set(0)
var11.set(0)
var12.set(0)
var13.set(0)
var14.set(0)
var15.set(0)
var16.set(0)
var17.set(0)
var18.set(0)
var19.set(0)
var20.set(0)
var21.set(0)
var22.set(0)
var23.set(0)
var24.set(0)

varFries = StringVar()
varSalad = StringVar()
varHamburger = StringVar()
varOnion = StringVar()
varChicken = StringVar()
varFish = StringVar()
varBeefSand = StringVar()
varChickenSand = StringVar()

varFries.set("0")
varSalad.set("0")
varHamburger.set("0")
varOnion.set("0")
varChicken.set("0")
varFish.set("0")
varBeefSand.set("0")
varChickenSand.set("0")

# ==========================
varHashBrown = StringVar()
varToastedBagel = StringVar()
varPancakes = StringVar()
varPineapple = StringVar()
varChocolate = StringVar()

varHashBrown.set("0")
varToastedBagel.set("0")
varPancakes.set("0")
varPineapple.set("0")
varChocolate.set("0")

#=======================
varTea = StringVar()
varCola = StringVar()
varCoffee = StringVar()
varOrange = StringVar()
varWater = StringVar()

varTea.set("0")
varCola.set("0")
varCoffee.set("0")
varOrange.set("0")
varWater.set("0")


##=======================
varCone = StringVar()
varShake = StringVar()
varStrawberry = StringVar()

varCone.set("0")
varShake.set("0")
varStrawberry.set("0")

#=========================
varHanuman = StringVar()
varAngkor = StringVar()
varAnchor = StringVar()

varHanuman.set("0")
varAngkor.set("0")
varAnchor.set("0")

